# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Title
title: [Pattern Recognition and Deep Learning (PRDL) Reading Group]
description: [Reading Group for discussing and disseminating state-of-the-art papers in Deep Learning , Pattern Recognition and Computer Vision]
